spring.jpa:
  datgabase: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-52-206-38-187.compute-1.amazonaws.com/d4lv9os41apc0m
  username: apyykizfotpncl
  password: ec881c9d78fc08ca1824abb1c06ca255a1d1434421934594939a52c00320f24e
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: project.sns-application.secret_key
  # 30days
  token.expired-time-ms: 2592000000